[package]
name = "edge_detection_visual"
version = "0.1.1"
authors = ["Jia Ye <planet0104@gmail.com>"]
edition = "2021"

[dependencies]
image = "0.24.7"
rand = "0.8.5"
slint = "1.3.0"
imageproc = "0.23.0"
anyhow = "1"